import os
import re

replacements = {
    r'\bnao\b': 'não',
    r'\bNao\b': 'Não',
    r'\bRecomendacao\b': 'Recomendação',
    r'\bTecnica\b': 'Técnica',
    r'\bTecnico\b': 'Técnico',
    r'\btecnico\b': 'técnico',
    r'\bclassificacao\b': 'classificação',
    r'\bClassificacao\b': 'Classificação',
    r'\bpopulacao\b': 'população',
    r'\bPopulacao\b': 'População',
    r'\bavaliacao\b': 'avaliação',
    r'\bAvaliacao\b': 'Avaliação',
    r'\bdiagnostico\b': 'diagnóstico',
    r'\bDiagnostico\b': 'Diagnóstico',
    r'\bautossuficiencia\b': 'autossuficiência',
    r'\bAutossuficiencia\b': 'Autossuficiência',
    r'\bregiao\b': 'região',
    r'\bRegiao\b': 'Região',
    r'\bgeografica\b': 'geográfica',
    r'\bGeografica\b': 'Geográfica',
    r'\blogistica\b': 'logística',
    r'\bLogistica\b': 'Logística',
    r'\bsaude\b': 'saúde',
    r'\bSaude\b': 'Saúde',
    r'\bpolitica\b': 'política',
    r'\bPolitica\b': 'Política',
    r'\beconomica\b': 'econômica',
    r'\bEconomica\b': 'Econômica',
    r'\beconomico\b': 'econômico',
    r'\bEconomico\b': 'Econômico',
    r'\bterritorio\b': 'território',
    r'\bTerritorio\b': 'Território',
    r'\beducacao\b': 'educação',
    r'\bEducacao\b': 'Educação',
    r'\bbasica\b': 'básica',
    r'\bBasica\b': 'Básica',
    r'\bbasico\b': 'básico',
    r'\bBasico\b': 'Básico',
    r'\btelecomunicacoes\b': 'telecomunicações',
    r'\bTelecomunicacoes\b': 'Telecomunicações',
    r'\bseguranca\b': 'segurança',
    r'\bSeguranca\b': 'Segurança',
    r'\bmitigacao\b': 'mitigação',
    r'\bMitigacao\b': 'Mitigação',
    r'\bdossie\b': 'dossiê',
    r'\bDossie\b': 'Dossiê',
    r'\banalise\b': 'análise',
    r'\bAnalise\b': 'Análise',
    r'\bestrategica\b': 'estratégica',
    r'\bEstrategica\b': 'Estratégica',
    r'\bestrategico\b': 'estratégico',
    r'\bEstrategico\b': 'Estratégico',
    r'\bestraté gico': 'estratégico',
    r'\batraves\b': 'através',
    r'\bAtraves\b': 'Através',
    r'\barea\b': 'área',
    r'\bArea\b': 'Área',
    r'\bareas\b': 'áreas',
    r'\bAreas\b': 'Áreas',
    r'\bcriterio\b': 'critério',
    r'\bCriterio\b': 'Critério',
    r'\bmedio\b': 'médio',
    r'\bMedio\b': 'Médio',
    r'\bperiodo\b': 'período',
    r'\bPeriodo\b': 'Período',
    r'\binfluencia\b': 'influência',
    r'\bInfluencia\b': 'Influência',
    r'\bagraria\b': 'agrária',
    r'\bAgraria\b': 'Agrária',
    r'\bagricola\b': 'agrícola',
    r'\bAgricola\b': 'Agrícola',
    r'\bpecuaria\b': 'pecuária',
    r'\bPecuaria\b': 'Pecuária',
    r'\bindustria\b': 'indústria',
    r'\bIndustria\b': 'Indústria',
    r'\bcomercio\b': 'comércio',
    r'\bComercio\b': 'Comércio',
    r'\bservicos\b': 'serviços',
    r'\bServicos\b': 'Serviços',
    r'\bpublicos\b': 'públicos',
    r'\bPublicos\b': 'Públicos',
    r'\bpublica\b': 'pública',
    r'\bPublica\b': 'Pública',
    r'\brodoviaria\b': 'rodoviária',
    r'\bRodoviaria\b': 'Rodoviária',
    r'\bclimatica\b': 'climática',
    r'\bClimatica\b': 'Climática',
    r'\bmigracao\b': 'migração',
    r'\bMigracao\b': 'Migração',
    r'\bdemografica\b': 'demográfica',
    r'\bDemografica\b': 'Demográfica',
    r'\beletrica\b': 'elétrica',
    r'\bEletrica\b': 'Elétrica',
    r'\bagua\b': 'água',
    r'\bAgua\b': 'Água',
    r'\bcomunicacao\b': 'comunicação',
    r'\bComunicacao\b': 'Comunicação',
    r'\bmovel\b': 'móvel',
    r'\bMovel\b': 'Móvel',
    r'\bsatelite\b': 'satélite',
    r'\bSatelite\b': 'Satélite',
    r'\binovacao\b': 'inovação',
    r'\bInovacao\b': 'Inovação',
    r'\bciencia\b': 'ciência',
    r'\bCiencia\b': 'Ciência',
    r'\bcapacitacao\b': 'capacitação',
    r'\bCapacitacao\b': 'Capacitação',
    r'\bpatrimonio\b': 'patrimônio',
    r'\bPatrimonio\b': 'Patrimônio',
    r'\bhistorico\b': 'histórico',
    r'\bHistorico\b': 'Histórico',
    r'\bjustica\b': 'justiça',
    r'\bJustica\b': 'Justiça',
    r'\bparticipacao\b': 'participação',
    r'\bParticipacao\b': 'Participação',
    r'\badministracao\b': 'administração',
    r'\bAdministracao\b': 'Administração',
    r'\bgestao\b': 'gestão',
    r'\bGestao\b': 'Gestão',
    r'\btransparencia\b': 'transparência',
    r'\bTransparencia\b': 'Transparência',
    r'\bcorrupcao\b': 'corrupção',
    r'\bCorrupcao\b': 'Corrupção',
    r'\betica\b': 'ética',
    r'\bEtica\b': 'Ética',
    r'\bexpressao\b': 'expressão',
    r'\bExpressao\b': 'Expressão',
    r'\breligiao\b': 'religião',
    r'\bReligiao\b': 'Religião',
    r'\bopiniao\b': 'opinião',
    r'\bOpiniao\b': 'Opinião',
    r'\bmidia\b': 'mídia',
    r'\bMidia\b': 'Mídia',
    r'\binformacao\b': 'informação',
    r'\bInformacao\b': 'Informação',
    r'\bviolencia\b': 'violência',
    r'\bViolencia\b': 'Violência',
    r'\btrafico\b': 'tráfico',
    r'\bTrafico\b': 'Tráfico',
    r'\bameaca\b': 'ameaça',
    r'\bAmeaca\b': 'Ameaça',
    r'\bantropico\b': 'antrópico',
    r'\bAntropico\b': 'Antrópico',
    r'\bemergencia\b': 'emergência',
    r'\bEmergencia\b': 'Emergência',
    r'\bhumanitaria\b': 'humanitária',
    r'\bHumanitaria\b': 'Humanitária',
    r'\bresiliencia\b': 'resiliência',
    r'\bResiliencia\b': 'Resiliência',
    r'\badaptacao\b': 'adaptação',
    r'\bAdaptacao\b': 'Adaptação',
    r'\bmudanca\b': 'mudança',
    r'\bMudanca\b': 'Mudança',
    r'\brenovaveis\b': 'renováveis',
    r'\bRenovaveis\b': 'Renováveis',
    r'\bpoluicao\b': 'poluição',
    r'\bPoluicao\b': 'Poluição',
    r'\bconservacao\b': 'conservação',
    r'\bConservacao\b': 'Conservação',
    r'\bpreservacao\b': 'preservação',
    r'\bPreservacao\b': 'Preservação',
    r'\bconscientizacao\b': 'conscientização',
    r'\bConscientizacao\b': 'Conscientização',
    r'\bgeracoes\b': 'gerações',
    r'\bGeracoes\b': 'Gerações',
    r'\bhistoria\b': 'história',
    r'\bHistoria\b': 'História',
    r'\bmemoria\b': 'memória',
    r'\bMemoria\b': 'Memória',
    r'\borganizacao\b': 'organização',
    r'\bOrganizacao\b': 'Organização',
    r'\bassociacao\b': 'associação',
    r'\bAssociacao\b': 'Associação',
    r'\bconexao\b': 'conexão',
    r'\bConexao\b': 'Conexão',
    r'\bcolaboracao\b': 'colaboração',
    r'\bColaboracao\b': 'Colaboração',
    r'\bcooperacao\b': 'cooperação',
    r'\bCooperacao\b': 'Cooperação',
    r'\btolerancia\b': 'tolerância',
    r'\bTolerancia\b': 'Tolerância',
    r'\binclusao\b': 'inclusão',
    r'\bInclusao\b': 'Inclusão',
    r'\bConsolidacao\b': 'Consolidação',
    r'\bcalibracao\b': 'calibração',
    r'\bpublicacao\b': 'publicação',
    r'\bCapitulo\b': 'Capítulo',
    r'\bCapitulos\b': 'Capítulos',
    r'\bmedia\b': 'média',
    r'\bMedia\b': 'Média',
    r'\breferencia\b': 'referência',
    r'\bReferencia\b': 'Referência',
    r'\blocalizacao\b': 'localização',
    r'\bhidrologico\b': 'hidrológico',
    r'\bindice\b': 'índice',
    r'\bestacao\b': 'estação',
    r'\bconvergencia\b': 'convergência',
    r'\boperacao\b': 'operação',
    r'\bparaguai\b': 'Paraguai',
    r'\bParaguay\b': 'Paraguai',
    r'\bhistorica\b': 'histórica',
    r'\bagrario\b': 'agrário',
    r'\bpecuario\b': 'pecuário',
    r'\bservico\b': 'serviço',
    r'\bpublico\b': 'público',
    r'\brodoviario\b': 'rodoviário',
    r'\bferroviario\b': 'ferroviário',
    r'\bhidroviario\b': 'hidroviário',
    r'\bclimatico\b': 'climático',
    r'\bdemografico\b': 'demográfico',
    r'\beletrico\b': 'elétrico',
    r'\bresiduo\b': 'resíduo',
    r'\bsolido\b': 'sólido',
    r'\buniversitario\b': 'universitário',
    r'\bgeracao\b': 'geração',
    r'\brenovavel\b': 'renovável',
    r'\bConvergência\b': 'Convergencia',
    # Geographic Names - Restore Spanish original
    r'\bAssunção\b': 'Asuncion',
    r'\bAsunción\b': 'Asuncion',
    r'\bConcepção\b': 'Concepcion',
    r'\bConcepción\b': 'Concepcion',
    r'\bCaacupé\b': 'Caacupe',
    r'\bCaaguazú\b': 'Caaguazu',
    r'\bCaazapá\b': 'Caazapa',
    r'\bEncarnação\b': 'Encarnacion',
    r'\bEncarnación\b': 'Encarnacion',
    r'\bGuairá\b': 'Guaira',
    r'\bItapúa\b': 'Itapua',
    r'\bParaguarí\b': 'Paraguari',
    r'\bÑeembucú\b': 'Neembucu',
    r'\bCanindeyú\b': 'Canindeyu',
    r'\bBoquerón\b': 'Boqueron',
}

skip_pattern = re.compile(r'(\\(?:label|ref|cite|url|href|include|input|usepackage|documentclass)\{[^}]*\})')

def safe_replace(content):
    parts = skip_pattern.split(content)
    new_parts = []
    for i, part in enumerate(parts):
        if i % 2 == 0:
            for pattern, replacement in replacements.items():
                part = re.sub(pattern, replacement, part)
            new_parts.append(part)
        else:
            new_parts.append(part)
    return "".join(new_parts)

def process_file(filepath):
    print(f"Processando {filepath}...")
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    new_content = safe_replace(content)
    
    if content != new_content:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"Alterações salvas em {filepath}.")
    else:
        print(f"Sem alterações em {filepath}.")

def main():
    for root, dirs, files in os.walk('livro_latex'):
        for file in files:
            if file.endswith('.tex'):
                process_file(os.path.join(root, file))

if __name__ == "__main__":
    main()
